source :rubygems

gem "sinatra"             # 1.3.2
gem "sinatra-contrib"     # 1.3.1

gem "datamapper"          # 1.2.0
gem "dm-sqlite-adapter"   # 1.2.0

gem "slim"                # 1.1.0
gem "thin"                # 1.3.1

gem "rack-test"           # ~>0.6.1
