source 'http://rubygems.org'

gem 'rails', '3.0.1'
# gem 'jammit', '0.5.3'
# gem 'yui-compressor', '0.9.2', :git => "git://github.com/sstephenson/ruby-yui-compressor.git"
# gem 'closure-compiler', '0.3.3', :git =>"git://github.com/documentcloud/closure-compiler.git"
